[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"

[tool.poetry.dev-dependencies]
fake-bpy-module-latest = "^20240718"
pyright = "*"
ruff = "*"

[tool.pyright]
typeCheckingMode = "standard"
